### ISSUE TITLE
Firefox 40 - Plugin dont work more

### ISSUE THREAD

**Issue by RogerSik** [bahbka/selfoss-notify#2]
Hello,

with the upgrade from Firefox 39 to Firefox 40 the plugin doens't appear more on the menu toolbar.

**Comment by bahbka** [comment]
Yep :( I'll try to fix it this weekend.

**Comment by fabsmusicjunkie** [comment]
good to know, it's not a configuration problem

**Comment by bahbka** [comment]
I uploaded new version 0.9.0 to Mozilla, waiting for validation now. You can [update it manualy](https://addons.mozilla.org/firefox/addon/selfoss-notify/versions/0.9.0), or it will be updated automaticaly after successful validation.
Added support for Firefox >= 38, also fixed some old bugs, and added new :)
